/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day13

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

fun <T>assertIn(element:T, collection: Collection<T>): Unit {
    assert(element in collection, { -> "$element is not in $collection"})
}

class Day13Test {
    @Test
    fun testInit() {
        val scenario = Day13Scenario()
        assertEquals(21, scenario.lines.size)
        assertEquals(18, scenario.points.size)
        assertEquals(10 to 4, scenario.points[4])
    }

    @Test
    fun testFoldingAxes() {
        val scenario = Day13Scenario()
        assertEquals(listOf(0 to 7, 5 to 0), scenario.foldingAxes)
    }

    @Test
    fun testFoldOnce() {
        val scenario = Day13Scenario()
        scenario.foldOnce(scenario.foldingAxes[0])
        assertIn(0 to 0, scenario.points)
        assertIn(2 to 0, scenario.points)
        assertIn(3 to 0, scenario.points)
    }

    @Test
    fun testCountAfterFolds() {
        val scenario = Day13Scenario()
        scenario.foldOnce(scenario.foldingAxes[0])
        assertEquals(17, scenario.points.size)
    }

    @Test 
    fun testDrawAfterAllFolds() {
        val scenario = Day13Scenario()
        scenario.foldAll()
        assertEquals(16, scenario.points.size)
        assertEquals(listOf("#####", "#...#", "#...#", "#...#", "#####"), scenario.drawFoldedSheet())
    }
}
