/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day4

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day4Test {
    @Test
    fun testInit() {
        val scenario = Day4Scenario()
        assertEquals(19, scenario.lines.size)
        assertEquals(
                listOf(
                        22,
                        13,
                        17,
                        11,
                        0,
                        8,
                        2,
                        23,
                        4,
                        24,
                        21,
                        9,
                        14,
                        16,
                        7,
                        6,
                        10,
                        3,
                        18,
                        5,
                        1,
                        12,
                        20,
                        15,
                        19
                ),
                scenario.boards[0].numberGrid
        )
        assertEquals(25, scenario.boards[0].marked.size)
    }

    @Test
    fun testCallNumber() {
        val scenario = Day4Scenario()
        scenario.callNumber(7)
        assertEquals(true, scenario.boards[0].marked[14])
        assertEquals(true, scenario.boards[1].marked[12])
        assertEquals(true, scenario.boards[2].marked[24])
    }

    @Test
    fun testIsGameFinished() {
        val scenario = Day4Scenario()
        scenario.callNumber(7)
        scenario.callNumber(4)
        scenario.callNumber(9)
        scenario.callNumber(5)
        scenario.callNumber(11)
        scenario.callNumber(17)
        scenario.callNumber(23)
        scenario.callNumber(2)
        scenario.callNumber(0)
        scenario.callNumber(14)
        scenario.callNumber(21)
        assertEquals(false, scenario.isGameFinished())
        scenario.callNumber(24)
        assertEquals(true, scenario.isGameFinished())
    }

    @Test
    fun testGetFinalScore() {
        val scenario = Day4Scenario()
        assertEquals(4512, scenario.getFinalScore())
    }

    @Test
    fun testGetFinalScoreLast() {
        println("[----- LAST GAME -----]")
        val scenario = Day4Scenario()
        assertEquals(1924, scenario.getFinalScore(last = true))
    }
}
