/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day9

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day9Test {
    @Test
    fun testInit() {
        val scenario = Day9Scenario()
        assertEquals(5, scenario.heightmap.size)
        assertEquals(10, scenario.heightmap[0].size)
    }

    @Test
    fun testPopulateLowPoints() {
        val scenario = Day9Scenario()
        assertEquals(mutableListOf(1 to 0, 9 to 0, 2 to 2, 6 to 4), scenario.lowPoints)
    }

    @Test
    fun testRiskLevel() {
        val scenario = Day9Scenario()
        assertEquals(2, scenario.evaluateRiskLevel(1, 0))
        assertEquals(1, scenario.evaluateRiskLevel(9, 0))
        assertEquals(0, scenario.evaluateRiskLevel(7, 0))
    }

    @Test
    fun testTotalRiskLevel() {
        val scenario = Day9Scenario()
        assertEquals(15, scenario.evaluateTotalRiskLevel())
    }

    @Test
    fun testPopulateBasins() {
        val scenario = Day9Scenario()
        assertEquals(mutableSetOf(1 to 0, 0 to 0, 0 to 1), scenario.basins.get(1 to 0))
        assertEquals(
                mutableSetOf(
                        9 to 0,
                        8 to 0,
                        7 to 0,
                        6 to 0,
                        5 to 0,
                        9 to 1,
                        8 to 1,
                        6 to 1,
                        9 to 2
                ),
                scenario.basins.get(9 to 0)
        )
    }

    @Test
    fun testMultiplyThreeLargestBasinSizes() {
        val scenario = Day9Scenario()
        assertEquals(1134, scenario.multiplyThreeLargestBasinSizes())
    }
}
