/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day10

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day10Test {
    @Test
    fun testInit() {
        val scenario = Day10Scenario()
        assertEquals(10, scenario.lines.size)
    }

    @Test
    fun testFirstCorruptedCharacter() {
        val scenario = Day10Scenario()
        assertEquals(null, scenario.getFirstCorruptedCharacter(scenario.lines[0]))
        assertEquals('}', scenario.getFirstCorruptedCharacter(scenario.lines[2]))
    }

    @Test
    fun testCorruptionScore() {
        val scenario = Day10Scenario()
        assertEquals(26397, scenario.computeCorruptionScore())
    }

    @Test
    fun testCompleteLine() {
        val scenario = Day10Scenario()
        assertEquals("])}>", scenario.completeLine("<{([{{}}[<[[[<>{}]]]>[]]"))
    }

    @Test
    fun testIncompletionScore() {
        val scenario = Day10Scenario()
        assertEquals(288957, scenario.computeIncompletionScore("[({(<(())[]>[[{[]{<()<>>"))
        assertEquals(5566, scenario.computeIncompletionScore("[(()[<>])]({[<{<<[]>>("))
        assertEquals(1480781, scenario.computeIncompletionScore("(((({<>}<{<{<>}{[]{[]{}"))
        assertEquals(995444, scenario.computeIncompletionScore("{<[[]]>}<{[{[{[]{()[[[]"))
        assertEquals(294, scenario.computeIncompletionScore("<{([{{}}[<[[[<>{}]]]>[]]"))
    }

    @Test
    fun testTotalIncompletionScore() {
        val scenario = Day10Scenario()
        assertEquals(288957, scenario.computeTotalIncompletionScore())
    }
}
