/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.duprat.aoc2021.day6

import dev.duprat.aoc2021.utils.Scenario

class Day6Scenario : Scenario {
    val lanternFishes: MutableList<Int> = mutableListOf()

    var day = 0

    val lanternFishSpawnCounter = 6
    val newLanternFishFirstCounter = 8

    constructor() : super() {
        lanternFishes.addAll(lines[0].split(",").map { it.toInt() })
    }

    fun reset() {
        lanternFishes.clear()
        lanternFishes.addAll(lines[0].split(",").map { it.toInt() })
        day = 0
    }

    fun addDay() {
        val schoolSize = lanternFishes.size
        for (i in 0 until schoolSize) {
            lanternFishes[i]--
            if (lanternFishes[i] < 0) {
                lanternFishes[i] = lanternFishSpawnCounter
                lanternFishes.add(newLanternFishFirstCounter)
            }
        }
        day++
    }

    fun countLanternFishesAfterDays(days: Int): Int {
        if (days < day) reset()
        (day until days).forEach { addDay() }
        return lanternFishes.size
    }
}
