/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day8

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day8Test {
    @Test
    fun testInit() {
        val scenario = Day8Scenario()
        assertEquals(10, scenario.lines.size)
        assertEquals(
                listOf(
                        "be",
                        "cfbegad",
                        "cbdgef",
                        "fgaecd",
                        "cgeb",
                        "fdcge",
                        "agebfd",
                        "fecdb",
                        "fabcd",
                        "edb"
                ),
                scenario.signalPatterns[0]
        )
        assertEquals(listOf("fdgacbe", "cefdb", "cefbgd", "gcbe"), scenario.outputSignals[0])
    }

    @Test
    fun testCountEasyDigits() {
        val scenario = Day8Scenario()
        assertEquals(26, scenario.countEasyDigits())
    }

    @Test
    fun testDecodeOutput() {
        val scenario = Day8Scenario()
        assertEquals(
                8394,
                scenario.decodeOutput(scenario.signalPatterns[0], scenario.outputSignals[0])
        )

        assertEquals(
                9361,
                scenario.decodeOutput(scenario.signalPatterns[3], scenario.outputSignals[3])
        )
    }

    @Test
    fun testSumAllOutputs() {
        val scenario = Day8Scenario()
        assertEquals(61229, scenario.sumAllOutputs())
    }
}
