/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day17

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day17Test {
    @Test
    fun testInit() {
        val scenario = Day17Scenario()
        assertEquals(1, scenario.lines.size)
        assertEquals(20..30, scenario.xRange)
        assertEquals(-10..-5, scenario.yRange)
    }

    @Test
    fun testShot7x2y() {
        val shot = Shot(7, 2)
        assertEquals(true, shot.shootAtTarget(20..30, -10..-5))
    }

    @Test
    fun testShot6x3y() {
        val shot = Shot(6, 3)
        assertEquals(true, shot.shootAtTarget(20..30, -10..-5))
    }

    @Test
    fun testShot9x0y() {
        val shot = Shot(9, 0)
        assertEquals(true, shot.shootAtTarget(20..30, -10..-5))
    }

    @Test
    fun testShot17x_4y() {
        val shot = Shot(17, -4)
        assertEquals(false, shot.shootAtTarget(20..30, -10..-5))
    }

    @Test
    fun testShot6x9y() {
        val shot = Shot(6, 9)
        assertEquals(true, shot.shootAtTarget(20..30, -10..-5))
        assertEquals(45, shot.maxY)
    }

    @Test
    fun testHighestShot() {
        val scenario = Day17Scenario()
        assertEquals(45, scenario.findHighestShotInTarget())
    }

    @Test
    fun testEveryShotInTarget() {
        val scenario = Day17Scenario()
        assertEquals(112, scenario.findEveryShotInTarget().size)
    }
}
