/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day6

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day6Test {
    @Test
    fun testInit() {
        val scenario = Day6Scenario()
        assertEquals(1, scenario.lines.size)
        assertEquals(5, scenario.lanternFishes.size)
    }

    @Test
    fun testAddDay() {
        val scenario = Day6Scenario()
        scenario.addDay()
        assertEquals(5, scenario.lanternFishes.size)
        scenario.addDay()
        assertEquals(6, scenario.lanternFishes.size)
        assertEquals(8, scenario.lanternFishes.last())
    }

    @Test
    fun testCountLanternFishesAfterDays() {
        val scenario = Day6Scenario()
        assertEquals(26, scenario.countLanternFishesAfterDays(18))
        assertEquals(5934, scenario.countLanternFishesAfterDays(80))
    }
}
