/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day6

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day6V2Test {
    @Test
    fun testInit() {
        val scenario = Day6ScenarioVariant(2)
        assertEquals(1, scenario.lines.size)
        assertEquals(5, scenario.initialLanternFishes.size)
    }

    @Test
    fun testCountLanternFishesAfter18Days() {
        val scenario = Day6ScenarioVariant(18)
        assertEquals(26, scenario.countLanternFishes())
    }

    @Test
    fun testCountLanternFishesAfter80Days() {
        val scenario = Day6ScenarioVariant(80)
        assertEquals(5934, scenario.countLanternFishes())
    }

    @Test
    fun testCountLanternFishesAfter256Days() {
        val scenario = Day6ScenarioVariant(256)
        assertEquals(26984457539, scenario.countLanternFishes())
    }
}
