/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day7

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day7Test {
    @Test
    fun testInit() {
        val scenario = Day7Scenario()
        assertEquals(1, scenario.lines.size)
        assertEquals(10, scenario.crabPositions.size)
    }

    @Test
    fun testConsumptionToAlignAt() {
        val scenario = Day7Scenario()
        assertEquals(41, scenario.getConsumptionToAlignAt(1))
        assertEquals(39, scenario.getConsumptionToAlignAt(3))
        assertEquals(71, scenario.getConsumptionToAlignAt(10))
        assertEquals(37, scenario.getConsumptionToAlignAt(2))
    }

    @Test
    fun testLowestConsumption() {
        val scenario = Day7Scenario()
        assertEquals(37, scenario.getLowestConsumption())
    }

    @Test
    fun testCrabEngConsumptionToAlignAt() {
        val scenario = Day7Scenario(true)
        assertEquals(206, scenario.getConsumptionToAlignAt(2))
        assertEquals(168, scenario.getConsumptionToAlignAt(5))
    }

    @Test
    fun testCrabEngLowestConsumption() {
        val scenario = Day7Scenario(true)
        assertEquals(168, scenario.getLowestConsumption())
    }
}
