/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.duprat.aoc2021.day16

import dev.duprat.aoc2021.utils.Scenario
import dev.duprat.aoc2021.utils.hex2bin

class Day16Scenario : Scenario {
  val inputPacket: Packet

  constructor() : super() {
    inputPacket = decodePacket(lines[0])
  }

  fun decodePacket(hex: String): Packet {
    val bin = hex2bin(hex)
    val packetTypeID = bin.slice(3..5).toInt(2)
    if (packetTypeID == 4) return LiteralValuePacket(bin)
    return OperatorPacket(bin)
  }
}

fun main() {
  val scenario = Day16Scenario()
  println("Exercice 1")
  println(scenario.inputPacket.computePacketHierarchy())
  println("Exercice 2")
  println(scenario.inputPacket.value)
}
