/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.duprat.aoc2021.day15

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

@kotlin.ExperimentalStdlibApi
class Day15Test {
    @Test
    fun testInit() {
        val scenario = Day15Scenario()
        assertEquals(10, scenario.riskLevels.size)
        assertEquals(10, scenario.accumulatedRiskPathGrid.size)
    }

    @Test
    fun testScanRisks() {
        val scenario = Day15Scenario()
        val hasChanged = scenario.scanRisks()
        assertEquals(true, hasChanged)
        assertEquals(40, scenario.accumulatedRiskPathGrid[9][9])
    }

    @Test
    fun testLowestPath() {
        val scenario = Day15Scenario()
        assertEquals(40, scenario.computeLowestRisk())
    }

    @Test
    fun testMultipleTiles() {
        val scenario = Day15Scenario(5)
        assertEquals(50, scenario.riskLevels.size)
        assertEquals(9, scenario.riskLevels[3][2])
        assertEquals(1, scenario.riskLevels[13][2])
        assertEquals(2, scenario.riskLevels[23][2])
        assertEquals(1, scenario.riskLevels[3][12])
        assertEquals(2, scenario.riskLevels[13][12])
        assertEquals(50, scenario.accumulatedRiskPathGrid.size)
    }

    @Test
    fun testLowestPathMultipleTiles() {
        val scenario = Day15Scenario(5)
        assertEquals(315, scenario.computeLowestRisk())
    }
}
